/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gerenciador_de_senhas;

import control.ControlUsuario;
import dao.Conexao;
import gerenciador_de_senhas.model.ModelUsuario;
import java.awt.Point;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author fernando.oliveira
 */
public class ViewUsuario extends javax.swing.JFrame {

    ControlUsuario controlUsuario = new ControlUsuario();
    ArrayList<ModelUsuario> listamModelUsuario = new ArrayList<ModelUsuario>();
    int p_troca = 0;
    /**
     * Creates new form ViewUsuario
     */
    public ViewUsuario() throws SQLException {
        initComponents();
        carregarUsuarios();
        
    }

    //SETAR CAMPOS
    private void setarCampos() throws ParseException, SQLException {
        int setar = tblUsuario.getSelectedRow();
        ControlUsuario control = new ControlUsuario();
        ModelUsuario modelusuario = new ModelUsuario();
        String tag = tblUsuario.getModel().getValueAt(setar, 4).toString();
        modelusuario = control.controlSelectUser(tag);

        txtNome.setText(tblUsuario.getModel().getValueAt(setar, 1).toString());
        txtGrupo.setSelectedItem(modelusuario.getGrupo());
        txtMaquina.setText(modelusuario.getMaquina());
        txtAnydesk.setText(modelusuario.getAnydesk());
        txtDescricao.setText(modelusuario.getDescricacao());
        txtLocalidade.setText(modelusuario.getLocalidade());
        txtEmail.setText(modelusuario.getEmail());
        txtTag.setText(modelusuario.getTag());
        txtContato.setText(modelusuario.getContato());

        //selecao();
    }

//LISTAR USUARIOS    
    private void carregarUsuarios() throws SQLException {

        listamModelUsuario = controlUsuario.getListaAppControl(cbGrupo.getSelectedItem().toString());
        DefaultTableModel modelo = (DefaultTableModel) tblUsuario.getModel();

        modelo.setNumRows(0);
        //CARREGA OS DADOS DA LISTA NA TABELA
        int cont = listamModelUsuario.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listamModelUsuario.get(i).getId(),
                listamModelUsuario.get(i).getNome(),
                listamModelUsuario.get(i).getGrupo(),
                listamModelUsuario.get(i).getMaquina(),
                listamModelUsuario.get(i).getTag(),
                listamModelUsuario.get(i).getDescricacao(),
                listamModelUsuario.get(i).getLocalidade()
            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbColumn = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnVisu = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaquina = new javax.swing.JTextField();
        txtAnydesk = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtLocalidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTag = new javax.swing.JTextField();
        txtContato = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtGrupo = new javax.swing.JComboBox<>();
        cbGrupo = new javax.swing.JComboBox<>();
        btnRel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        btnEdit1 = new javax.swing.JButton();
        txtTag1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/computer.png"))); // NOI18N
        jMenuItem1.setText("Troca de Computador");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change.png"))); // NOI18N
        jMenuItem3.setText("Trocar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Controle de Usuario");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Pesquisar Nome");

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Grupo");

        cbColumn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOME", "TAG", "MAQUINA" }));
        cbColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbColumnActionPerformed(evt);
            }
        });

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Grupo", "Maquina", "Service TAG"
            }
        ));
        tblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuarioMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblUsuarioMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuario);
        if (tblUsuario.getColumnModel().getColumnCount() > 0) {
            tblUsuario.getColumnModel().getColumn(0).setMinWidth(30);
            tblUsuario.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblUsuario.getColumnModel().getColumn(0).setMaxWidth(50);
            tblUsuario.getColumnModel().getColumn(1).setMinWidth(300);
            tblUsuario.getColumnModel().getColumn(1).setPreferredWidth(300);
            tblUsuario.getColumnModel().getColumn(1).setMaxWidth(300);
        }

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciador_de_senhas/img/marca-de-verificacao.png"))); // NOI18N
        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnVisu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVisu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciador_de_senhas/img/oculos-de-leitura-vintage.png"))); // NOI18N
        btnVisu.setText("Visualizar");
        btnVisu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisuActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciador_de_senhas/img/editar-texto.png"))); // NOI18N
        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciador_de_senhas/img/deletar-lixeira.png"))); // NOI18N
        btnDel.setText("Remover");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        txtNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel4.setText("Nome");

        jLabel5.setText("Setor");

        jLabel6.setText("Maquina");

        jLabel7.setText("Anydesk");

        jLabel8.setText("Descrição");

        jLabel9.setText("Localidade");

        jLabel10.setText("Email");

        jLabel11.setText("Service Tag");

        jLabel12.setText("Contato");

        txtGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MS TECH", "MS BANK", "MSBB MONEY", "CLOUDBREAK", "CORRESPONDENTE", "PC-RESERVA", "EXTRAVIADO" }));
        txtGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrupoActionPerformed(evt);
            }
        });

        cbGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MS TECH", "MS BANK", "MSBB MONEY", "CLOUDBREAK", "CORRESPONDENTE", "PC-RESERVA", "EXTRAVIADO" }));
        cbGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGrupoActionPerformed(evt);
            }
        });

        btnRel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciador_de_senhas/img/relatorio.png"))); // NOI18N
        btnRel.setText("Relatorios");
        btnRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelActionPerformed(evt);
            }
        });

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane2.setViewportView(txtDescricao);

        btnEdit1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEdit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gerenciador_de_senhas/img/ID-Card-icon.png"))); // NOI18N
        btnEdit1.setText("Novo");
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });

        txtTag1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTag1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Patrimonio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAnydesk, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(txtLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(186, 186, 186)
                                        .addComponent(jLabel9)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addGap(187, 187, 187)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(151, 151, 151)
                                        .addComponent(jLabel12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(151, 151, 151)
                                        .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbColumn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(23, 23, 23)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(cbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(301, 301, 301)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(txtTag, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(txtTag1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnAdd)
                        .addGap(24, 24, 24)
                        .addComponent(btnVisu)
                        .addGap(12, 12, 12)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRel)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPesquisar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addComponent(cbColumn, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel12)))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAnydesk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTag1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnVisu)
                    .addComponent(btnDel)
                    .addComponent(btnRel)
                    .addComponent(btnEdit1)
                    .addComponent(btnEdit))
                .addGap(10, 10, 10))
        );

        setSize(new java.awt.Dimension(786, 769));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            ModelUsuario modeloUsuario = new ModelUsuario();
            ControlUsuario controlUsuario = new ControlUsuario();
            modeloUsuario.setNome(txtNome.getText().toUpperCase());
            modeloUsuario.setGrupo(txtGrupo.getSelectedItem().toString());
            modeloUsuario.setMaquina(txtMaquina.getText().toUpperCase());
            modeloUsuario.setAnydesk(txtAnydesk.getText());
            modeloUsuario.setDescricacao(txtDescricao.getText().toUpperCase());
            modeloUsuario.setLocalidade(txtLocalidade.getText().toUpperCase());
            modeloUsuario.setEmail(txtEmail.getText());
            modeloUsuario.setTag(txtTag.getText().toUpperCase());
            modeloUsuario.setContato(txtContato.getText());
            controlUsuario.verificaUsuario(modeloUsuario);

            txtNome.setText("");
            //  txtGrupo.setText("");
            txtMaquina.setText("");
            txtAnydesk.setText("");
            txtDescricao.setText("");
            txtLocalidade.setText("");
            txtEmail.setText("");
            txtTag.setText("");
            txtContato.setText("");
            carregarUsuarios();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnVisuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnVisuActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        try {
            ControlUsuario control = new ControlUsuario();
            int selecao = tblUsuario.getSelectedRow();
            int id = Integer.parseInt(tblUsuario.getModel().getValueAt(selecao, 0).toString());

            ModelUsuario modelUsuario = new ModelUsuario();
            modelUsuario.setId(id);
            modelUsuario.setNome(txtNome.getText().toUpperCase());
            modelUsuario.setGrupo(txtGrupo.getSelectedItem().toString());
            modelUsuario.setMaquina(txtMaquina.getText().toUpperCase());
            modelUsuario.setAnydesk(txtAnydesk.getText());
            modelUsuario.setDescricacao(txtDescricao.getText().toUpperCase());
            modelUsuario.setLocalidade(txtLocalidade.getText().toUpperCase());
            modelUsuario.setEmail(txtEmail.getText());
            modelUsuario.setTag(txtTag.getText().toUpperCase());
            modelUsuario.setContato(txtContato.getText());

            control.controlEditUsuario(modelUsuario);
            txtNome.setText("");
            txtMaquina.setText("");
            txtAnydesk.setText("");
            txtDescricao.setText("");
            txtLocalidade.setText("");
            txtEmail.setText("");
            txtTag.setText("");
            txtContato.setText("");
            carregarUsuarios();
        } catch (ParseException ex) {
            Logger.getLogger(ViewPass.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ViewPass.class.getName()).log(Level.SEVERE, null, ex);
        } finally {

            JOptionPane.showMessageDialog(null, "Dados Editados com sucesso...");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void cbColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbColumnActionPerformed

    }//GEN-LAST:event_cbColumnActionPerformed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased

        ControlUsuario controlUsuario = new ControlUsuario();

        try {
            String usuario = txtPesquisar.getText();
            String column = cbColumn.getSelectedItem().toString();
            tblUsuario.setModel(DbUtils.resultSetToTableModel(controlUsuario.controlSelect(usuario, column)));
            //System.out.print());
        } catch (SQLException ex) {
            Logger.getLogger(ViewUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ViewUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void tblUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuarioMouseClicked
        try {
            // TODO add your handling code here:
            txtDescricao.setText("");
            setarCampos();
        } catch (ParseException ex) {
            Logger.getLogger(ViewPass.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ViewUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblUsuarioMouseClicked

    private void txtGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrupoActionPerformed

    private void cbGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGrupoActionPerformed
        try {

            carregarUsuarios();
        } catch (SQLException ex) {
            Logger.getLogger(ViewUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cbGrupoActionPerformed

    private void btnRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelActionPerformed
        ViewRelatorio rel = null;
        rel = new ViewRelatorio();
        rel.getInstance().setVisible(true);
        rel.toFront();
    }//GEN-LAST:event_btnRelActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        try {
            int selecao = tblUsuario.getSelectedRow();
            int id = Integer.parseInt(tblUsuario.getModel().getValueAt(selecao, 0).toString());

            ModelUsuario modelUsuario = new ModelUsuario();
            modelUsuario.setId(id);
            modelUsuario.setNome(txtNome.getText());
            System.out.print(modelUsuario.getAnydesk());
            ControlUsuario control = new ControlUsuario();
            control.controlRemoveUsuario(modelUsuario);
            carregarUsuarios();
        } catch (SQLException ex) {
            Logger.getLogger(ViewPass.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ViewUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } finally {

            JOptionPane.showMessageDialog(null, "Dados Removido com sucesso...");
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed

        try {
            txtNome.setText("");
            //  txtGrupo.setText("");
            txtMaquina.setText("");
            txtAnydesk.setText("");
            txtDescricao.setText("");
            txtLocalidade.setText("");
            txtEmail.setText("");
            txtTag.setText("");
            txtContato.setText("");
            carregarUsuarios();
        } catch (SQLException ex) {
            Logger.getLogger(ViewUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEdit1ActionPerformed
    
    private void tblUsuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuarioMouseReleased
        int setar = tblUsuario.getSelectedRow();
        String grupo = tblUsuario.getModel().getValueAt(setar, 2).toString();
               
        if (!grupo.equals("PC-RESERVA")) {
            if (evt.isPopupTrigger()) {
                int x = evt.getX();
                int y = evt.getY();
                JComponent source = (JComponent) evt.getSource();
                SwingUtilities.convertPointToScreen(new Point(x, y), source);
                jPopupMenu1.show(source, x, y);
                p_troca = 1;
            }
        }
        else if(grupo.equals("PC-RESERVA") && p_troca == 1){
                if (evt.isPopupTrigger()) {
                int x = evt.getX();
                int y = evt.getY();
                JComponent source = (JComponent) evt.getSource();
                SwingUtilities.convertPointToScreen(new Point(x, y), source);
                jPopupMenu2.show(source, x, y);
            }
        }
    }//GEN-LAST:event_tblUsuarioMouseReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        cbGrupo.setSelectedIndex(5);
        cbGrupo.setEnabled(false);
       
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
         cbGrupo.setEnabled(true);
         p_troca = 0;
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void txtTag1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTag1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTag1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ViewUsuario().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ViewUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnRel;
    private javax.swing.JButton btnVisu;
    private javax.swing.JComboBox<String> cbColumn;
    private javax.swing.JComboBox<String> cbGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblUsuario;
    private javax.swing.JTextField txtAnydesk;
    private javax.swing.JTextField txtContato;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JComboBox<String> txtGrupo;
    private javax.swing.JTextField txtLocalidade;
    private javax.swing.JTextField txtMaquina;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtTag;
    private javax.swing.JTextField txtTag1;
    // End of variables declaration//GEN-END:variables
}
